from __future__ import annotations

import json
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from edgerunner.task_config import (  # noqa: E402
    TaskSettings,
    load_all_task_settings,
    override_env_var,
)

WORKFLOW_DIR = ROOT / ".github" / "workflows"
GENERATED_MARKER = "# Generated by scripts/generate_workflows.py"
TASK_NAME_PATTERN = re.compile(r"^[A-Za-z0-9_-]+$")

# Third-party actions are pinned to a commit SHA rather than a tag. A tag such as
# `v4` is mutable, so whoever controls the upstream repo can change what runs here
# and read this workflow's GCP credentials. The trailing comment records the human
# readable version the SHA corresponded to when it was pinned.
#
# To refresh a pin:
#   git ls-remote https://github.com/OWNER/REPO refs/tags/vN
ACTION_CHECKOUT = "actions/checkout@11d5960a326750d5838078e36cf38b85af677262"  # v4.4.0
ACTION_SETUP_PYTHON = "actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065"  # v5.6.0
ACTION_CACHE = "actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830"  # v4.3.0
ACTION_GCP_AUTH = "google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093"  # v3.0.0


def load_tasks() -> dict[str, TaskSettings]:
    tasks = load_all_task_settings(ROOT / "config" / "tasks.toml")
    for task in tasks.values():
        validate_task(task)
    return tasks


def validate_task(task: TaskSettings) -> None:
    if not TASK_NAME_PATTERN.fullmatch(task.name):
        raise ValueError(f"Invalid task name: {task.name}")
    if not (ROOT / task.script_path).is_file():
        raise ValueError(f"Task script does not exist: {task.script_path}")
    if not task.cron_setting.strip():
        raise ValueError(f"Task '{task.name}' is missing cron_setting")
    if not task.sheet_id.strip():
        raise ValueError(f"Task '{task.name}' is missing sheet_id")
    if not task.tab_name.strip():
        raise ValueError(f"Task '{task.name}' is missing tab_name")
    task.manual_overrides


def workflow_yaml(task: TaskSettings) -> str:
    job_name = f"run-{task.name}".replace("_", "-")
    workflow_dispatch_inputs = workflow_dispatch_inputs_yaml(task)
    run_step = run_step_yaml(task)
    auth_step = ""
    if task.gcp_auth:
        auth_step = f"""
      - name: Authenticate to Google Cloud
        uses: {ACTION_GCP_AUTH}
        with:
          workload_identity_provider: ${{{{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}}}
          service_account: ${{{{ secrets.GCP_SERVICE_ACCOUNT }}}}
"""

    return f"""{GENERATED_MARKER}
name: {task.name}

on:
  workflow_dispatch:{workflow_dispatch_inputs}
  schedule:
    - cron: "{task.cron_setting}"

permissions:
  contents: read
  id-token: write

jobs:
  {job_name}:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: {ACTION_CHECKOUT}

      - name: Set up Python
        uses: {ACTION_SETUP_PYTHON}
        with:
          python-version: "3.11"
          cache: pip

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
{auth_step}
      - name: Restore dlt state
        uses: {ACTION_CACHE}
        with:
          path: |
            .dlt
            *.duckdb
            *.duckdb.wal
          key: dlt-${{{{ runner.os }}}}-{task.name}-${{{{ github.run_id }}}}
          restore-keys: |
            dlt-${{{{ runner.os }}}}-{task.name}-

{run_step}
"""


def workflow_dispatch_inputs_yaml(task: TaskSettings) -> str:
    overrides = task.manual_overrides
    if not overrides:
        return ""

    lines = ["", "    inputs:"]
    for override in overrides:
        lines.extend(
            [
                f"      {override['name']}:",
                f"        description: {_yaml_string(override['description'])}",
                "        required: false",
                "        type: string",
            ]
        )
    return "\n".join(lines)


def run_step_yaml(task: TaskSettings) -> str:
    lines = [f"      - name: Run {task.name}"]
    overrides = task.manual_overrides
    if overrides:
        lines.append("        env:")
        for override in overrides:
            env_var = override_env_var(override["name"])
            input_name = override["name"]
            lines.append(f"          {env_var}: ${{{{ github.event.inputs.{input_name} || '' }}}}")
    lines.append(f"        run: python {task.script_path} --task-name {task.name}")
    return "\n".join(lines)


def _yaml_string(value: str) -> str:
    return json.dumps(value)


def main() -> None:
    WORKFLOW_DIR.mkdir(parents=True, exist_ok=True)
    tasks = load_tasks()

    for workflow_path in WORKFLOW_DIR.glob("*.yml"):
        if workflow_path.stem not in tasks and GENERATED_MARKER in workflow_path.read_text(
            encoding="utf-8"
        ):
            workflow_path.unlink()
            print(f"Removed {workflow_path.relative_to(ROOT)}")

    for task in tasks.values():
        workflow_path = WORKFLOW_DIR / f"{task.name}.yml"
        workflow_path.write_text(workflow_yaml(task), encoding="utf-8", newline="\n")
        print(f"Wrote {workflow_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
