from __future__ import annotations

from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from edgerunner.task_config import TaskSettings, load_all_task_settings  # noqa: E402

WORKFLOW_DIR = ROOT / ".github" / "workflows"
GENERATED_MARKER = "# Generated by scripts/generate_workflows.py"
TASK_NAME_PATTERN = re.compile(r"^[A-Za-z0-9_-]+$")


def load_tasks() -> dict[str, TaskSettings]:
    tasks = load_all_task_settings(ROOT / "config" / "tasks.toml")
    for task in tasks.values():
        validate_task(task)
    return tasks


def validate_task(task: TaskSettings) -> None:
    if not TASK_NAME_PATTERN.fullmatch(task.name):
        raise ValueError(f"Invalid task name: {task.name}")
    if not (ROOT / task.script_path).is_file():
        raise ValueError(f"Task script does not exist: {task.script_path}")
    if not task.cron_setting.strip():
        raise ValueError(f"Task '{task.name}' is missing cron_setting")
    if not task.sheet_id.strip():
        raise ValueError(f"Task '{task.name}' is missing sheet_id")
    if not task.tab_name.strip():
        raise ValueError(f"Task '{task.name}' is missing tab_name")


def workflow_yaml(task: TaskSettings) -> str:
    job_name = f"run-{task.name}".replace("_", "-")
    auth_step = ""
    if task.gcp_auth:
        auth_step = """
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
"""

    return f"""{GENERATED_MARKER}
name: {task.name}

on:
  workflow_dispatch:
  schedule:
    - cron: "{task.cron_setting}"

permissions:
  contents: read
  id-token: write

jobs:
  {job_name}:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
{auth_step}
      - name: Restore dlt state
        uses: actions/cache@v4
        with:
          path: |
            .dlt
            *.duckdb
            *.duckdb.wal
          key: dlt-${{{{ runner.os }}}}-{task.name}-${{{{ github.run_id }}}}
          restore-keys: |
            dlt-${{{{ runner.os }}}}-{task.name}-

      - name: Run {task.name}
        run: python {task.script_path} --task-name {task.name}
"""


def main() -> None:
    WORKFLOW_DIR.mkdir(parents=True, exist_ok=True)
    tasks = load_tasks()

    for workflow_path in WORKFLOW_DIR.glob("*.yml"):
        if workflow_path.stem not in tasks and GENERATED_MARKER in workflow_path.read_text(
            encoding="utf-8"
        ):
            workflow_path.unlink()
            print(f"Removed {workflow_path.relative_to(ROOT)}")

    for task in tasks.values():
        workflow_path = WORKFLOW_DIR / f"{task.name}.yml"
        workflow_path.write_text(workflow_yaml(task), encoding="utf-8", newline="\n")
        print(f"Wrote {workflow_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
