from __future__ import annotations

import json
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from edgerunner.task_config import (  # noqa: E402
    TaskSettings,
    load_all_task_settings,
    override_env_var,
)

WORKFLOW_DIR = ROOT / ".github" / "workflows"
GENERATED_MARKER = "# Generated by scripts/generate_workflows.py"
TASK_NAME_PATTERN = re.compile(r"^[A-Za-z0-9_-]+$")
WORKFLOW_FILE_PATTERN = re.compile(r"^[A-Za-z0-9_.-]+$")

# GitHub only offers "Run workflow" for workflows that already exist on the
# default branch, so a workflow added on a testing branch cannot be dispatched
# until it merges. This file is generated unconditionally and never deleted, so
# it is always on the default branch and can be dispatched against any branch.
# Its display name stays constant for the same reason: GitHub lists workflows by
# the default branch's name, so a name that changed per branch would be
# confusing in the Actions sidebar.
TEST_WORKFLOW_STEM = "test_workflow"
TEST_WORKFLOW_NAME = "test workflow"
SCHEDULE_TIMEZONE = "America/New_York"

# Third-party actions are pinned to a commit SHA rather than a tag. A tag such as
# `v4` is mutable, so whoever controls the upstream repo can change what runs here
# and read this workflow's GCP credentials. The trailing comment records the human
# readable version the SHA corresponded to when it was pinned.
#
# To refresh a pin:
#   git ls-remote https://github.com/OWNER/REPO refs/tags/vN
ACTION_CHECKOUT = "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"  # v6.0.2
ACTION_SETUP_PYTHON = "actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405"  # v6.2.0
ACTION_GCP_AUTH = "google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093"  # v3.0.0


def load_tasks() -> dict[str, TaskSettings]:
    tasks = load_all_task_settings(ROOT / "config" / "tasks.toml")
    for task in tasks.values():
        validate_task(task)
    return tasks


def validate_task(task: TaskSettings) -> None:
    if not TASK_NAME_PATTERN.fullmatch(task.name):
        raise ValueError(f"Invalid task name: {task.name}")
    if not (ROOT / task.script_path).is_file():
        raise ValueError(f"Task script does not exist: {task.script_path}")
    if workflow_stem(task) == TEST_WORKFLOW_STEM:
        raise ValueError(
            f"Task '{task.name}' generates the workflow file name "
            f"'{TEST_WORKFLOW_STEM}.yml', which the framework reserves for the "
            "manual test slot. Rename the task or move its script into a group "
            "folder under tasks/."
        )
    task.manual_overrides


def select_test_task(tasks: dict[str, TaskSettings]) -> TaskSettings | None:
    # The test slot holds one task at a time, so ambiguity has to be an error
    # rather than a silent pick: generating the wrong task here means dispatching
    # the wrong task against a testing branch.
    test_tasks = [task for task in tasks.values() if task.is_test]
    if len(test_tasks) > 1:
        names = ", ".join(task.name for task in test_tasks)
        raise ValueError(
            f"Only one task may set is_test = true, but {len(test_tasks)} do: {names}. "
            "The test workflow holds a single task, so set is_test = false on all "
            "but the one you are currently testing."
        )
    return test_tasks[0] if test_tasks else None


def workflow_yaml(task: TaskSettings) -> str:
    job_name = f"run-{re.sub(r'[^A-Za-z0-9]+', '-', workflow_stem(task)).strip('-')}"
    return _task_workflow_yaml(
        task,
        display_name=workflow_display_name(task),
        job_name=job_name,
        schedule_yaml=schedule_trigger_yaml(task),
    )


def test_workflow_yaml(task: TaskSettings | None) -> str:
    if task is None:
        return empty_test_workflow_yaml()
    # No schedule: the slot exists for manual dispatch, and the task's own
    # generated workflow already carries its cron_setting.
    return _task_workflow_yaml(
        task,
        display_name=TEST_WORKFLOW_NAME,
        job_name="run-test-workflow",
        schedule_yaml="",
        describe_task=True,
        header_comment=(
            f"# Manual test slot, currently holding the task '{task.name}' because it\n"
            "# sets is_test = true in config/tasks.toml. Regenerated by\n"
            "# scripts/generate_workflows.py whenever that config changes."
        ),
    )


def empty_test_workflow_yaml() -> str:
    return f"""{GENERATED_MARKER}
# Manual test slot, currently empty because no task sets is_test = true in
# config/tasks.toml.
#
# GitHub only offers "Run workflow" for workflows that exist on the default
# branch, so a workflow added on a testing branch cannot be dispatched until it
# merges. This file is always present on the default branch to close that gap:
# set is_test = true on one task, push your testing branch, then run this
# workflow and pick that branch.
name: {_yaml_string(TEST_WORKFLOW_NAME)}

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-workflow-slot:
    runs-on: ubuntu-latest
    steps:
      - name: Report that no task is selected
        run: |
          echo "No task sets is_test = true in config/tasks.toml."
          echo "Set is_test = true on the task you want to test, commit so the"
          echo "workflow regenerates, push the branch, then run this workflow again."
          echo "Only one task may set is_test = true at a time."
"""


def _task_workflow_yaml(
    task: TaskSettings,
    *,
    display_name: str,
    job_name: str,
    schedule_yaml: str,
    header_comment: str = "",
    describe_task: bool = False,
) -> str:
    workflow_dispatch_inputs = workflow_dispatch_inputs_yaml(task)
    run_step = run_step_yaml(task)
    describe_step = f"\n{describe_step_yaml(task)}\n" if describe_task else ""
    alert_step = alert_step_yaml(task)

    permissions_yaml = "  contents: read"
    auth_step = ""
    if task.gcp_auth:
        permissions_yaml = f"{permissions_yaml}\n  id-token: write"
        auth_step = f"""
      - name: Authenticate to Google Cloud
        uses: {ACTION_GCP_AUTH}
        with:
          workload_identity_provider: ${{{{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}}}
          service_account: ${{{{ secrets.GCP_SERVICE_ACCOUNT }}}}
"""

    header = f"{GENERATED_MARKER}\n{header_comment}" if header_comment else GENERATED_MARKER

    return f"""{header}
name: {_yaml_string(display_name)}

on:
  workflow_dispatch:{workflow_dispatch_inputs}{schedule_yaml}

permissions:
{permissions_yaml}

jobs:
  {job_name}:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: {ACTION_CHECKOUT}

      - name: Set up Python
        uses: {ACTION_SETUP_PYTHON}
        with:
          python-version: "3.11"
{describe_step}
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
{auth_step}
{run_step}

{alert_step}
"""


def workflow_dispatch_inputs_yaml(task: TaskSettings) -> str:
    overrides = task.manual_overrides
    if not overrides:
        return ""

    lines = ["", "    inputs:"]
    for override in overrides:
        lines.extend(
            [
                f"      {override['name']}:",
                f"        description: {_yaml_string(override['description'])}",
                "        required: false",
                "        type: string",
            ]
        )
    return "\n".join(lines)


def schedule_trigger_yaml(task: TaskSettings) -> str:
    cron_setting = task.cron_setting.strip()
    if not cron_setting:
        return ""
    return (
        f'\n  schedule:\n    - cron: "{cron_setting}"'
        f'\n      timezone: "{SCHEDULE_TIMEZONE}"'
    )


def override_env_lines(task: TaskSettings) -> list[str]:
    """Env entries that pass workflow_dispatch inputs through to the task."""
    return [
        f"          {override_env_var(override['name'])}: "
        f"${{{{ github.event.inputs.{override['name']} || '' }}}}"
        for override in task.manual_overrides
    ]


def describe_step_yaml(task: TaskSettings) -> str:
    # The slot is always named "test workflow", so the run page cannot tell you
    # which task it holds. Report it before the slow install and auth steps, and
    # read the config at run time rather than baking values in here, so a slot
    # generated from a stale config is visible as a mismatch.
    lines = [
        f"      - name: Report the task under test ({task.name})",
        "        shell: bash",
        "        env:",
        "          PYTHONPATH: src",
    ]
    lines.extend(override_env_lines(task))
    lines.extend(
        [
            "        run: |",
            f"          python scripts/describe_task.py --task-name {task.name}",
        ]
    )
    return "\n".join(lines)


def run_step_yaml(task: TaskSettings) -> str:
    lines = [
        f"      - name: Run {task.name}",
        "        id: run_task",
        "        shell: bash",
        "        env:",
        "          TASK_LOG: task.log",
    ]
    lines.extend(override_env_lines(task))
    lines.extend(
        [
            "        run: |",
            "          set +e",
            f"          python {task.script_path} --task-name {task.name} 2>&1 | tee \"$TASK_LOG\"",
            "          status=${PIPESTATUS[0]}",
            '          echo "exit_code=$status" >> "$GITHUB_OUTPUT"',
            '          exit "$status"',
        ]
    )
    return "\n".join(lines)


def alert_step_yaml(task: TaskSettings) -> str:
    return """      - name: Send Slack alert
        if: always()
        run: |
          python scripts/send_slack_alert.py \\
            --webhook-url "${{ secrets.SLACK_WEBHOOK_URL }}" \\
            --task-name __TASK_NAME__ \\
            --task-outcome "${{ steps.run_task.outcome || 'not_run' }}" \\
            --task-exit-code "${{ steps.run_task.outputs.exit_code || 'unknown' }}" \\
            --job-status "${{ job.status }}" \\
            --task-log task.log \\
            --run-url "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \\
            --repository "${{ github.repository }}" \\
            --workflow-name "${{ github.workflow }}" \\
            --branch-name "${{ github.ref_name }}" \\
            --trigger "${{ github.event_name }}"
""".replace("__TASK_NAME__", _yaml_string(task.name))


def workflow_stem(task: TaskSettings) -> str:
    group = task_group(task)
    stem = f"{group}__{task.name}" if group else task.name
    if not WORKFLOW_FILE_PATTERN.fullmatch(stem):
        raise ValueError(f"Invalid workflow file name for task '{task.name}': {stem}")
    return stem


def workflow_display_name(task: TaskSettings) -> str:
    group = task_group(task)
    return f"{group} / {task.name}" if group else task.name


def task_group(task: TaskSettings) -> str | None:
    script_path = Path(task.script_path)
    parts = script_path.parts
    if len(parts) >= 3 and parts[0] == "tasks":
        return parts[1]
    return None


def _yaml_string(value: str) -> str:
    return json.dumps(value)


def write_workflows(tasks: dict[str, TaskSettings] | None = None) -> None:
    WORKFLOW_DIR.mkdir(parents=True, exist_ok=True)
    if tasks is None:
        tasks = load_tasks()
    test_task = select_test_task(tasks)

    # The test slot is kept even though no task owns it, so that it stays on the
    # default branch and remains dispatchable from any branch.
    expected_workflow_stems = {workflow_stem(task) for task in tasks.values()}
    expected_workflow_stems.add(TEST_WORKFLOW_STEM)
    for workflow_path in WORKFLOW_DIR.glob("*.yml"):
        if (
            workflow_path.stem not in expected_workflow_stems
            and GENERATED_MARKER in workflow_path.read_text(encoding="utf-8")
        ):
            workflow_path.unlink()
            print(f"Removed {workflow_path.relative_to(ROOT)}")

    for task in tasks.values():
        workflow_path = WORKFLOW_DIR / f"{workflow_stem(task)}.yml"
        workflow_path.write_text(
            workflow_yaml(task).rstrip() + "\n",
            encoding="utf-8",
            newline="\n",
        )
        print(f"Wrote {workflow_path.relative_to(ROOT)}")

    test_workflow_path = WORKFLOW_DIR / f"{TEST_WORKFLOW_STEM}.yml"
    test_workflow_path.write_text(
        test_workflow_yaml(test_task).rstrip() + "\n",
        encoding="utf-8",
        newline="\n",
    )
    holding = f"holding {test_task.name}" if test_task else "empty"
    print(f"Wrote {test_workflow_path.relative_to(ROOT)} ({holding})")


def main() -> None:
    write_workflows()


if __name__ == "__main__":
    main()
